version: '3.6'
services:
  #
  java:
    build: ./docker/java
    container_name: java
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./server/src:/usr/src:cached
    depends_on: #サービス間の依存関係を指定
      db:
        condition: service_started #db起動時に、appが起動する

  #dbサービス名（sql）    
  db: 
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./mysql/db:/var/lib/mysql  #実データ永続化
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: spring-boot-user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always

  volumes:
    mysql-data:
      driver: local